{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9ac260f-d846-4cec-ba84-ba400dcfdf70",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Ans\n",
    "\n",
    "Actually, exception class is superset of all errors and we know custom exception is user-defined exception class,\n",
    "we use it to fix/handle specific error but we don't know about all errors while writing code That's why we use Exception \n",
    "class while creating a Custom Exception.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d59853dd-af20-426c-9381-a5d298e2c6a2",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. Ans\n",
    "\n",
    "\n",
    "\n",
    "# import inspect module\n",
    "import inspect\n",
    "\n",
    "# our treeClass function\n",
    "def treeClass(self, ind = 0):\n",
    "    \n",
    "\n",
    "# print name of the class\n",
    "    print ('-' * ind, self.__name__)\n",
    "\n",
    "# iterating through subclasses\n",
    "    for i in self.__subclasses__():\n",
    "    \n",
    "        treeClass(i, ind + 3)\n",
    "\n",
    "print(\"Python Hierarchy exceptions is : \")\n",
    "\n",
    "# inspect.getmro() Return a tuple of class cls’s base classes.\n",
    "\n",
    "# building a tree hierarchy\n",
    "inspect.getclasstree(inspect.getmro(BaseException))\n",
    "\n",
    "# function call\n",
    "treeClass(BaseException)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d150043c-33cd-404c-9ce4-4284446a362e",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3.Ans\n",
    "\n",
    "\n",
    "ArithmeticError is simply an error that occurs during numeric calculations.\n",
    "\n",
    "ArithmeticError types in Python include:\n",
    "\n",
    "OverFlowError\n",
    "ZeroDivisionError\n",
    "FloatingPointError\n",
    "\n",
    "\n",
    "# ZeroDivision Error\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"errors.log\",level=logging.ERROR)\n",
    "\n",
    "try:\n",
    "    \n",
    "    a=4/0\n",
    "    \n",
    "except ArithmeticError as e:   # we can also use ZeroDivisionError\n",
    "    \n",
    "    logging.error(\"I am trying to handle ZeroDivision Error   {}\".format(e))\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "# OverFlowError\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"New_Error.log\",level=logging.ERROR)\n",
    "\n",
    "\n",
    "j = 5.0\n",
    "\n",
    "try:\n",
    "    for i in range(1, 1000):\n",
    "        j = j**i\n",
    "except ArithmeticError as e:\n",
    "    logging.error(\"I am try to handle Arithmetic Error {} {}\".format((e),(e.__class__)))\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "410ddf0d-e6ae-4f16-a266-5f26bac151ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Ans\n",
    "\n",
    "\n",
    "Because, Lookup Error acts as a base class for the exceptions that occur when a key or index used on a mapping or sequence\n",
    "of a list/dictionary is invalid or does not exists.\n",
    "\n",
    "The two types of exceptions raised are:\n",
    "\n",
    "KeyError\n",
    "IndexError\n",
    "\n",
    "# KeyError\n",
    "\n",
    "If a key we are trying to access is not found in the dictionary, a key error exception is raised.\n",
    "\n",
    "for example:-\n",
    "\n",
    "import logging\n",
    "\n",
    "\n",
    "\n",
    "logging.basicConfig(filename=\"Output.log\", level=logging.INFO)\n",
    "\n",
    "try:\n",
    "    dic={1:\"Rahul\",2:\"Rohan\"}\n",
    "   \n",
    "    logging.info(\"I am trying to print data %s\".format(dic[4]))\n",
    "                                                       \n",
    "                                                     \n",
    "                                                       \n",
    "except LookupError as e:\n",
    "                                                       \n",
    "    logging.error(\"Key not found {}\".format((e)))\n",
    "    \n",
    "    \n",
    "    \n",
    "# IndexError\n",
    "\n",
    "When we are trying to access an index (sequence) of a list that does not exist in that list or is out of range\n",
    "of that list, an index error is raised.\n",
    "\n",
    "For example:-\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"Output.log\",level=logging.INFO)\n",
    "\n",
    "try:  \n",
    "    a = ['a', 'b', 'c']  \n",
    "    \n",
    "    logging.info(\"I am trying to print a[4]\")\n",
    "    \n",
    "    print (a[4])  \n",
    "    \n",
    "except LookupError:  \n",
    "    logging.error(\"Index Error Exception Raised, list index out of range\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5855e718-9cbc-4fa0-b17c-1f1af985248c",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. Ans\n",
    "\n",
    "#Import Error\n",
    "\n",
    "ImportError is a type of error in python and it is raised when we try to import a module that does not exist (unable to load)\n",
    "in its standard path or even when we make a typo in the module's name.\n",
    "\n",
    "#Module NOt Found Error\n",
    "\n",
    "It is same as ImportError i.e when we try to find a Module but it does not exist in the package.\n",
    "\n",
    "\n",
    "For Example:-\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"New.log\", level=logging.INFO)\n",
    "\n",
    "try:\n",
    "    \n",
    "    import pwskill\n",
    "    \n",
    "except ModuleNotFoundError as e:\n",
    "    \n",
    "    logging.info(\"I am trying to handle ModuleNotFoundError\")\n",
    "    \n",
    "    logging.error(e)\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dbcc5712-0986-4aec-85d7-0aebeb144a13",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6.Ans\n",
    "\n",
    "Some best practice for exception handling in python are:-\n",
    "\n",
    "1. Use Exceptions for Exceptional Cases\n",
    "2. Don’t Swallow the Exception\n",
    "3. Catch Specific Exceptions\n",
    "4. Always Clean Up Resources in a Finally Block\n",
    "5. Avoid Raising Generic Exceptions\n",
    "6. Raise Custom Exceptions\n",
    "7. Define Your Own Exception Hierarchy\n",
    "8. Document All Exceptions Thrown by a Function\n",
    "9. Provide Contextual Information When Raising an Exception\n",
    "10. Write Tests to Ensure That Exceptions Are Raised Correctly\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
